<?php

/**
 * Created by PhpStorm.
 * User: alexander
 * Date: 01.11.17
 * Time: 22:31
 */

namespace AlexGunkel\ProjectOrganizerTest\View;

use AlexGunkel\ProjectOrganizer\AccessValidation\AccessValidatorInterface;
use AlexGunkel\ProjectOrganizer\Domain\Model\Project;
use AlexGunkel\ProjectOrganizer\View\ValidationLinkGenerator;
use PHPUnit\Framework\TestCase;

class ValidationLinkGeneratorTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $_SERVER['HTTP_HOST'] = 'http://test.ag';
    }

    /**
     * Test the correctness of generated links
     *
     * @param string $code
     * @param string $link
     *
     * @dataProvider buildCodesAndLinks
     *
     * @return void
     */
    public function testGenerateLink(string $code, int $pageId, string $link): void
    {
        $validatorMock = $this->getMockForAbstractClass(AccessValidatorInterface::class);
        $validatorMock->method('generateValidationCode')->willReturn($code);
        $object = new Project;
        $generator = new ValidationLinkGenerator($validatorMock);

        $this->assertSame(
            $link,
            $generator->generateLink($object, $pageId)
        );
    }

    public function buildCodesAndLinks(): array
    {
        return [
            ['test', 13, 'http://test.ag/index.php?id=13&code=test'],
        ];
    }
}